In [3]:
import pandas as pd

In [4]:
pd.__version__

'3.0.6'

In [5]:
df=pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.shape[0]

10000

In [8]:
df.fuel_type.nunique()

3

In [9]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
(df.isnull().sum() > 0).sum()

np.int64(2)

In [12]:
df.groupby('origin')['fuel_efficiency_mpg'].agg(['min', 'mean', 'max'])

         min       mean   max
origin
Asia    21.3  30.741015  41.2
Europe  20.7  30.552675  39.4
USA     19.8  29.097739  38.2

In [13]:
df.query("origin == 'Asia'")['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [14]:
median_before = df['horsepower'].median()
print(median_before)

254.0

In [15]:
most_frequent = df['horsepower'].mode()[0]
print(most_frequent)

252.0

In [16]:
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [17]:
median_after = df['horsepower'].median()
print(median_after)

252.0

select cars from Asia origin

In [18]:
cars_from_asia = df[df['origin']=='Asia']

Select only columns vehicle_weight and model_year

In [19]:
df_asia_filtered = cars_from_asia[['vehicle_weight', 'model_year']]

Select the first 7 values

In [20]:
df_asia_reduced = df_asia_filtered.iloc[:7, :]